### ISSUE TITLE
Example/ShowCase story giving out an error

### ISSUE THREAD

**Issue by DaeunYoon** [sidestream-tech/sidebase#15]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug
Show case story gives errors and doesn't show up on my mac.

When I ran `npm run story` after cloning the project locally, it gave console errors to me and the ShowCase example stories do not show up on historie. 

![image](https://user-images.githubusercontent.com/34188262/188440042-2b58cd70-1da2-4ca6-be00-0b1e863b1c3b.png)

### Additional context

I cloned the project to a new branch in an already existing project. 

### Logs

```shell
Error while collecting story /Users/daeunyoon/Sidestream/is-this-an-mlm/app/components/example/ShowCase.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#build/app.config.mjs" is not defined in package /Users/daeunyoon/Sidestream/is-this-an-mlm/app/node_modules/nuxt/package.json imported from /Users/daeunyoon/Sidestream/is-this-an-mlm/app/node_modules/nuxt/dist/app/config.mjs
    at new NodeError (node:internal/errors:371:5)
    at throwImportNotDefined (node:internal/modules/esm/resolve:429:9)
    at packageImportsResolve (node:internal/modules/esm/resolve:778:3)
    at moduleResolve (node:internal/modules/esm/resolve:924:21)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:1044:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

**Comment by BracketJohn** [comment]
Weird - can you reproduce it @zoey-kaiser?

**Comment by zoey-kaiser** [comment]
> Weird - can you reproduce it @zoey-kaiser?

I run into the same error! I have managed to trace the error back to the `nuxt-link` component we use. Maybe we configured it incorrectly inside the `preview.js` for historie?

I will continue looking into it and posting any results!

**Comment by BracketJohn** [comment]
> I run into the same error! I have managed to trace the error back to the nuxt-link component we use. 

nice work!

> Maybe we configured it incorrectly inside the preview.js for historie?

Hm, we don't have a preview.js for histpoire! It's vue + vite all the way down - looking forward to getting more insights here -> maybe an interesting learning for later.

**Comment by BracketJohn** [comment]
Yay - then let's close this for now (:
