### ISSUE TITLE
Nuxt server error on 'npm run dev'

### ISSUE THREAD

**Issue by DaeunYoon** [sidestream-tech/sidebase#16]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.9`
- Nitro Version:    `0.5.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Describe the bug

The nuxt server works with docker running, but when the server does not connect on docker, it gives a 500 server error. 
However, `npm run build` works fine in any scenario.

### Additional context

This seems similar as [reported nuxt bug](https://github.com/nuxt/framework/issues/7220)

### Logs

```shell
Nuxi 3.0.0-rc.9                                                               14:00:38
Nuxt 3.0.0-rc.9 with Nitro 0.5.1                                              14:00:38
                                                                              14:00:39
  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.2.109:3000/

ℹ Vite client warmed up in 541ms                                              14:00:41
ℹ Vite server warmed up in 139ms                                              14:00:41
✔ Nitro built in 530 ms                                                 nitro 14:00:42
DB: Initializing DB connection
DB: Successfully initialized database connection
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'modules')
  at _sfc_main.setup (./node_modules/nuxt/dist/app/components/nuxt-root.vue:67:16)  
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)  
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7107:29)  
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7062:11)  
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:172:17)  
  at renderToString (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:446:26)  
  at Object.renderToString$1 [as renderToString] (./.nuxt/dev/index.mjs:661:24)  
  at Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:173:40)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async ./.nuxt/dev/index.mjs:710:21
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <NuxtRoot>
```

**Comment by BracketJohn** [comment]
Thanks!

Seems to be related to RC.9, so if you're stuck right now as a work-around you can try downgrading your version to `RC.8` by doing:
```
npm i -D nuxt@3.0.0-rc.8

# clean all nuxt caches
npx nuxi-edge@latest cleanup

npm run dev
```

**Comment by zoey-kaiser** [comment]
I don't have any issues running RC.9 with NodeJS V18. That could also be another fix to your issue!

**Comment by a1xon** [comment]
Tried with node lts and latest. Both don't work. Maybe OS? I'm on Linux.

**Comment by BracketJohn** [comment]
Weird, in the meatime have you tried downgrading to rc8, the way I shared above?

**Comment by DaeunYoon** [comment]
I've tested with different node versions but didn't work for me as well. 
Downgrading to rc8 does work on my Mac thou.

**Comment by BracketJohn** [comment]
@a1xon, @rustre-undefined are you two still experiencing the error with the newest sidebase version?

**Comment by pi0** [comment]
Please check https://github.com/nuxt/framework/issues/7609 for root causes and solutions. It happens when vue dependency is installed in a parent directory with vite-node that is enabled by default for rc.9 and rc.10.

**Comment by BracketJohn** [comment]
Thanks! I think this closes the issue for now.

**If you are having this problem:** Checkout if you have another `vue` install in a parent directory. Remove it if possible, checkout https://github.com/nuxt/framework/issues/7609 for more information + workarounds.
