### ISSUE TITLE
Use `onBeforeUnmount` to destroy the Interval

### ISSUE THREAD

**Issue by ndianabasi** [sidestream-tech/sidebase#22]
### Describe the feature

I'm referring to these lines:

https://github.com/sidestream-tech/sidebase/blob/8afc4885ffba1f1c0718da4067b49f8b2fcf51ef/app/pages/index.vue#L13-L17

I think that using the `onBeforeUnmount` hook should preferred because you want to always have access to the reference to `refreshDataInterval` during the current lifecycle of the component. 

The current implementation uses `onBeforeMount` to attempt to clear an interval from a reference of a previous lifecycle. This cannot be guaranteed to work.

**Comment by BracketJohn** [comment]
Thanks for the request!

You're very right, I think this is likely a bug / oversight (: We will fix this!

**Comment by BracketJohn** [comment]
@ndianabasi we fixed it, let me know if something arises again and thank you so much for using sidebase + reporting this (:
