### ISSUE TITLE
Add TailwindCSS linting rules

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/sidebase#30]
### Describe the feature

There are several eslint extensions to enforce correct usage of TailwindCSS classes. I believe while very opinionated, these linters can add value and consistency to projects.

The office TailwindCSS Prettier package is this one:
https://www.npmjs.com/package/prettier-plugin-tailwindcss

This package sorts class names after TailwindCSS's offical class sorting guidelines: https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

Another interesting package is this community maintained one:
https://www.npmjs.com/package/eslint-plugin-tailwindcss

Along with class sorting this package also adds:
- enforces shorthands (mx-4 my-4 gets turned into m-4)
- disallows contradicting class names (mx-3 mx-4 on one element throws an error)

I feel like a mixture of both of these could be very helpful!

**Comment by BracketJohn** [comment]
Let's do it!

Can it be worked into eslint?

**Comment by zoey-kaiser** [comment]
Yes, it can. I can open a PR today which adds support. 

From what I wrote do you want only want the first package or a mix of both?

**Comment by BracketJohn** [comment]
Let's go with the eslint only variant as discussed: upside is that it is eslint based and gives us both kinds of rules.
