### ISSUE TITLE
Add testamonial

### ISSUE THREAD

**Issue by BracketJohn** [sidestream-tech/sidebase#7]
### Describe the feature

Add a testamonial we got for this project via our announcement tweet: https://twitter.com/i/timeline

> "Beautiful work on sidebase!" by https://github.com/Atinux, CEO of Nuxt

He send this to me via DM, I asked him if we can use it as a testamonial and he said yes ❤️ 

### Additional information

- [x] add to readme
- [ ] add to website

**Comment by BracketJohn** [comment]
@zoey-kaiser do you want to have a look if you can add it to the website quickly? avatar + quote would be nice.

**Comment by zoey-kaiser** [comment]
> @zoey-kaiser do you want to have a look if you can add it to the website quickly? avatar + quote would be nice.

Sure! The component is already finished but i did not add it as only showing one testimonial looked a bit sad. Do you have a few more for me? I always need:

- Name
- Avatar
- Screenshot of their comment

**Comment by BracketJohn** [comment]
for name + avatar: see https://github.com/Atinux github profile

> Screenshot of their comment

it was a twitter DM, I don't think that it would be super pleasent to put that into the website (: 

Here's a second testamonial: https://twitter.com/elbrujolegal/status/1571525564632113152

and I bet if we go through the feed of https://twitter.com/sidebase_io a bit more, we can find more

**Comment by zoey-kaiser** [comment]
Okay sounds good! Ill try and get at least a total of 5 and then I will add them. Do you want me to list them here beforehand so you can check them as well?

**Comment by BracketJohn** [comment]
I don't think we have to wait for 5, even if it's just 2 that'll be a sufficient start.

Just open a PR and ping and then we review them there (:
