### ISSUE TITLE
Design a website for SideBase.io

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/sidebase#9]
**Goal**
In order to present the features and benefits of SideBase, we are looking to launch a website. This is a preliminary planning issue in which we will collect the information we aim to provide and create mocks for the finished site. 

**Tasks**
- [x] Collect the information we want to show on the page
- [x] Create a mock for the design

**Comment by zoey-kaiser** [comment]
- Hero
- Video presentation
- Features
- Testimonials
  - We would have to collect some twitter posts
- Contact Section
  - Link to Github Issues
  - Link to SideStream Website?

**Comment by BracketJohn** [comment]
> Testimonials 

in addition we have one by @atinux, see #7

**Comment by zoey-kaiser** [comment]
<details><summary>Mock V1</summary>
<p>

![Sidebase io - Landing Page](https://user-images.githubusercontent.com/30908158/188414709-2fc07b30-5cb7-4532-87c2-d6935e6ba393.png)

</p>
</details>

Some open questions I have about branding are the following:

- What logo are we planing to use? Currently it looks like we use the SideStream Logo and SideBase written as plain text
- What are our brand colors for SideBase? At SideStream we use green, do we want to continue this color to stay consistent in our branding? (another plus, Nuxt uses green too!) Note: I used red in this initial mock, however this can be quickly changed.
- What legal requirements do we have to link to? Imprint etc.etc

**Comment by danielkremerov** [comment]
Mock looks great - ready for implementation from my side. Just not sure about structure of Testimonial component, maybe could just use screenshots for now to keep authenticity as high as possible.  They come from different places (dm's, comments etc.) so it's hard to have a common structure without losing some authenticity  

> What logo are we planing to use? Currently it looks like we use the SideStream Logo and SideBase written as plain text

I prefer a dedicated Logo, will take care of it asap.

> What are our brand colors for SideBase? At SideStream we use green, do we want to continue this color to stay consistent in our branding? 

Let's stay with existing colors for the mentioned reasons - @chanpignon can help you with the Design Guide etc. if needed.

> What legal requirements do we have to link to? Imprint etc.etc

Just link to [this](https://www.sidestream.tech/en/imprint) external page in the footer for now, rest comes later

**Comment by zoey-kaiser** [comment]
> Just not sure about structure of Testimonial component, maybe could just use screenshots for now to keep authenticity as high as possible. They come from different places (dm's, comments etc.) so it's hard to have a common structure without losing some authenticity

I agree with you here. Finding the line between design integrity and authenticity is always hard 🤔.
One idea I have is to make a grid field with the avatars (and maybe names) of the people who endorsed us. When clicking on one of the people, a lightbox opens displaying an image with their endorsement. This would allow us to keep the design intact but also be as detailed as possible when it comes to what and where they said something about our product 🤗. 


> I prefer a dedicated Logo, will take care of it asap.

Sounds good! I left enough space to switch text/logos when they are completed 🥳.

> Let's stay with existing colors for the mentioned reasons - @chanpignon can help you with the Design Guide etc. if needed.

Yes, that would be amazing 😍! 

> Just link to [this](https://www.sidestream.tech/en/imprint) external page in the footer for now, rest comes later

That is what I thought. In the mock I added a imprint button in the footer, which we can use to link it!

**Comment by zoey-kaiser** [comment]
> One idea I have is to make a grid field with the avatars (and maybe names) of the people who endorsed us. When clicking on one of the people, a lightbox opens displaying an image with their endorsement. This would allow us to keep the design intact but also be as detailed as possible when it comes to what and where they said something about our product 🤗.

This is a quick mock up I created to show what I was thinking.

![Sidebase io](https://user-images.githubusercontent.com/30908158/188432645-f2f87cf6-73f9-4ffe-a6cf-0ac022ea5fd4.png)

**Comment by zoey-kaiser** [comment]
I really like the proposals you made! I think my favourite is the following: 

![Screenshot 2022-09-05 at 14 29 45](https://user-images.githubusercontent.com/30908158/188449671-be98ce61-51c6-44bd-ba2e-9ad9411b4d9e.png)

as it reminds me the most of the NuxtJS logo and I believe it would instantly help us associate with their brand (which is currently good, as we are focused on providing support for their product). 

> Also, if you need the colour codes, pls let me know (@zoey-kaiser I think).

It would be amazing if you could make me a Design Guide once we choose the logo. As long as I am still in the mocking process precise color codes are not as important yet, but once I begin work on the actual site it would be amazing to have a kit with logos and colors (also a favicon 😄). Can you also include the SideStream logo as I would like to add our company branding to the footer! 

> P.S. I like the proposal about the grid for the testimonials to keep it consistent but still having the option to show an image of the individual endorsement!

Thanks! I think it makes the most sense as well. I am not 100% happy with the way the mocked version looks, but I am sure it would look better in the final result! A few rounded edges maybe some shadows 😄

**Comment by chanpignon** [comment]
@zoey-kaiser alright! We (Daniel and I) agree on the logo mentioned by you. [Here](https://drive.google.com/file/d/1VPnrlrcXjOhOWCjx_R1vh1zCxIPid-2W/view?usp=sharing) you can find the logos in their dark and light versions as .png and .svg. Let me know once you need more information/files. :)

**Comment by BracketJohn** [comment]
Thanks for the feedback @valiafetisov - some of it hopefully made it in. The rest we can apply at a later point.

Closing this now as https://sidebase.io is online.
